### ISSUE TITLE
Incompatible with Snowy Pigs

### ISSUE THREAD

**Issue by Sunconure11** [DeflatedPickle/HungryPigs#2]
https://pastebin.com/1HGA1KXa

https://www.curseforge.com/minecraft/mc-mods/snow-pig-fabric

**Comment by Sunconure11** [comment]
@DeflatedPickle hello?

**Comment by Akairilia** [comment]
I also have the same issue. I disabled hungry pigs for now until it is fixed.

**Comment by Sunconure11** [comment]
Not stale, but the dev hasn’t gotten around to it
